env:
  - GO111MODULE=on
  - GOPROXY="https://gocenter.io"

builds:
  - binary: mcli
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

before:
  hooks:
    - go mod tidy

brews:
  - github:
      owner: drutbsov
      name: tap

    name: mcli
    homepage: "https://github.com/dmirubtsov/mcli"
    description: "A simple shortcut menu for shell commands"
